### PR TITLE
Fix tox configuration

### PR DESCRIPTION
**Pull request by aromanielloNTIA**
Switching the build system to hatchling broke the configuration for tox.

This update fixes the tox configuration, moves it to pyproject.toml, and updates the related part of the README.

A future version of tox will natively support configuration in pyproject.toml, rather than the legacy version currently implemented in this PR. (See https://github.com/tox-dev/tox/issues/999)

### CODE REVIEW

**Comment by ofek** [comment]
Would adding `isolated_build = true` under `[tox]` work instead?

**Comment by aromanielloNTIA** [comment]
@ofek I went back and forth about the best way to do this. When I use the tox config:

```ini
[tox]
envlist = py{38,39,310}
skip_missing_interpreters = True
isolated_build = True

[testenv]
deps =
    pytest >= 7.1.2
    pytest-cov >= 3.0.0
commands = pytest

...
```

I get: `WARNING: could not copy distfile to H:\.tox\distshare` at the beginning of the testing output when running `tox`.

The upside to the implementation in this PR is that this warning doesn't show up (I can't find much information about what its implications are), and the testing dependencies are only defined once in `pyproject.toml`. The downside is that additional `[dev]` dependencies are installed in the testing environments unnecessarily.

A better solution may be to create a new set of optional dependencies (listed under `[project.optional-dependencies]` in `pyproject.toml`) just for the testing environment. This would still require multiply-defined testing requirements. I would expect that when tox adds native support for `pyproject.toml` configuration, this will become a bit less awkward.

**Comment by ofek** [comment]
Have you tried Hatch environments?

**Comment by aromanielloNTIA** [comment]
@ofek We have internally discussed using Hatch for this repository after this issue was raised. We plan to test out Hatch and see if it is the solution we want to use longer-term, but for now we just want a quick fix for tox.

**Comment by ofek** [comment]
When the time comes, this:

```ini
[tox]
envlist = py{38,39,310}
skip_missing_interpreters = True
skipsdist = True

[testenv]
commands =
    pip install .[dev]
    pytest

[testenv:coverage]
commands =
    pip install .[dev]
    pytest --cov --cov-append --cov-report=term-missing --no-cov-on-fail
```

could become in a `hatch.toml`:

```toml
[[envs.default.matrix]]
python = ["38", "39", "310"]

[envs.default.scripts]
test = "pytest"
test-cov = "pytest --cov --cov-append --cov-report=term-missing --no-cov-on-fail"
```

**Comment by aromanielloNTIA** [comment]
Thanks for the feedback and assistance, @ofek!

**Review by jhazentia — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
